### ISSUE TITLE
Is it possible not to use Alamofire?

### ISSUE THREAD

**Issue by thinhv** [verygoodsecurity/vgs-collect-ios#120]
Hi, Alamofire seems to be quite bulky for a simple networking request. I would suggest to use URLSession to reduce the binary size.
Thank you!

**Comment by breferrari** [comment]
I agree on that. Would be really good for both users and VGS if Alamofire was removed.
Currently there's only one post request created on the APIClient that can be safely rewritten using URLSession instead.

**Comment by dmytrokhl** [comment]
Hi @thinhv @breferrari . I’m totally agree with you guys. Actually we already working on replacing Alamofire to native URLSession and it will be released in one of next releases https://github.com/verygoodsecurity/vgs-collect-ios/pull/114. The only one concern here is that Alamofire  provide nice AFError for failed requests, that will be replaced.

**Comment by dmytrokhl** [comment]
`Alamofire` has been removed as dependency in `VGSCollectSDK` [v1.5.0](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.5.0).
