### ISSUE TITLE
[FEATURE] A way for validating textField with type type none

### ISSUE THREAD

**Issue by siddharthsuneel-Deserve** [verygoodsecurity/vgs-collect-ios#136]
**Is your feature request related to a problem? Please describe.**
Input field validation is not available for the textfield with type none. Scenario when need to send some more data into vault other than the provided type and requirement is to validate it as well. It is not available as per current implementation.

**Describe the solution you'd like**
A way to inject custom validation or way of adding custom type with custom validation.
Inject a validation model with regex for a custom type.

**Describe alternatives you've considered**
NA

**Additional context**
This is very generic requirement which can be there for saving sensitive data other than card details into the vault and there is a requirement to validate it as well.

**Possible solution**
Don't have it right now, but can submitting a PR if asked.

**Comment by dmytrokhl** [comment]
Hello @siddharthsuneel-Deserve , we have this feature in our roadmap. For now it's possible to setup `configuration.formatPattern` string, this will limit the input length and prevent from adding not valid character types in `VGSTextfield`. To know when the input is full you can check `textfield.state.inputLength`. However for more complicated validations setting custom regex feature still required.

**Comment by dmytrokhl** [comment]
Hello @siddharthsuneel-Deserve, we released pre-build validation rules in `VGSCollectSDK` [v1.5.5](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.5.5). Now it's possible to add/edit validation rules to `VGSTextField` through it's configuration: 
```
configuration.validationRules = VGSValidationRuleSet(rules: [
    VGSValidationRuleLength(min: 6, max: 9, error: "WRONG LENGTH"),
    VGSValidationRulePattern(pattern: "^555\\d*$", error: "PATTERN FAILED")
  ])
```
Check our [documentation](https://www.verygoodsecurity.com/docs/vgs-collect/ios-sdk/error-handling) for more details.
