### ISSUE TITLE
[FEATURE] RTL support for VGSCardTextField

### ISSUE THREAD

**Issue by thinhv** [verygoodsecurity/vgs-collect-ios#138]
**Is your feature request related to a problem? Please describe.**
The card icon is alway on the right side. It should be `trailing` to have proper RightToLeft layout.
Also currently the card icon overlaps the textField.

**Describe the solution you'd like**
Please support RTL

**Additional context**
<img width="326" alt="Screenshot 2020-05-25 at 13 11 55" src="https://user-images.githubusercontent.com/12261314/82803535-6165ef80-9e89-11ea-9c03-6d71361b7678.png">

**Comment by dmytrokhl** [comment]
Hello @thinhv , changing icon side is planned to be available from next release https://github.com/verygoodsecurity/vgs-collect-ios/pull/111. Overlapping issue will be fixed there too.

**Comment by thinhv** [comment]
@dmytrokhl awesome. thank you

**Comment by dmytrokhl** [comment]
@thinhv this has been released in `VGSCollectSDK` [v1.5.1](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.5.1).
