### ISSUE TITLE
[ISSUE] Visa regex is incorrect.

### ISSUE THREAD

**Issue by DagAgren** [verygoodsecurity/vgs-collect-ios#154]
The validation regex for Visa is incorrect. Visa card numbers start with 4, and that seems to be the only rule. There are no limitation on the second digit.

https://baymard.com/checkout-usability/credit-card-patterns

This is a showstopper for us, as even several of our own developers have Visa cards that do not pass the current validation regex.

PR here: https://github.com/verygoodsecurity/vgs-collect-ios/pull/153

**Comment by dmytrokhl** [comment]
@DagAgren thanks for your PR. The fix released in [v1.5.3](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.5.3).
