### ISSUE TITLE
[ISSUE] Card number validation

### ISSUE THREAD

**Issue by isimpson** [verygoodsecurity/vgs-collect-ios#157]
We tested regexes from [SwiftLuhn.swift](https://github.com/verygoodsecurity/vgs-collect-ios/blob/master/Sources/VGSCollectSDK/UIElements/Text%20Field/Validation/Card/SwiftLuhn.swift) on our collection of real BINs and found that just over 5% of them fail.
Here's the collection of missing card bins: [missed_ios_bins.csv.zip](https://github.com/verygoodsecurity/vgs-collect-ios/files/4729339/missed_ios_bins.csv.zip)

Could you please give us an an ETA on fixing this? We're releasing a version with VGS support very soon and the issue can have a huge impact on our TTV.

See also the Android related issue: https://github.com/verygoodsecurity/vgs-collect-android/issues/64

**Comment by dmytrokhl** [comment]
Hello @isimpson . 

Our SDK supports only "global card numbers", but you still can send card numbers even they are not valid in SDK. For this, check that card number field configuration don't require valid only cards, so `configuration.isRequiredValidOnly = false`. Also you can ignore `textfield.state.isValid` attribute then.

The solution in future could be adding support of custom card brands, so developers can add specific card brands with data like validation regex, card image, etc.

**Comment by dmytrokhl** [comment]
We update the SDK with new features. Starting form [v1.6.0](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.6.0) it's possible to **add** your Custom Payment Card Brands, **edit** default Card Brands and **validate** `CardBrand.unknown` cards. 
Editing default Card Brands attributes and adding Custom Brands is available through `VGSPaymentCards` class. 
Validation of `CardBrand.unknown` cards can be turned on via `VGSValidationRulePaymentCard` in field configuration.

Check our [Docs](https://www.verygoodsecurity.com/docs/vgs-collect/ios-sdk/overview) for more details. Hope that will help with your issue.
