### ISSUE TITLE
[FEATURE] Add Swift Package Manager support

### ISSUE THREAD

**Issue by basememara** [verygoodsecurity/vgs-collect-ios#186]
We don't use 3rd party dependency managers. Is it possible to create as a Swift Package?

**Comment by dmytrokhl** [comment]
Hello @basememara, this is actually what we plan to do soon.

**Comment by basememara** [comment]
See pr #188 and #187

**Comment by dmytrokhl** [comment]
SwiftPM support is added in VGSCollectSDK [v1.7.0](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.7.0). Currently you can integrate only Core framework. We will add integration of 3d-party card scanning SDKs after they get updates with SwiftPM support.
