### ISSUE TITLE
Images missing when using Swift Package Manager

### ISSUE THREAD

**Issue by basememara** [verygoodsecurity/vgs-collect-ios#203]
Embedded resources were added in Swift 5.3, otherwise images for credit card types and any other assets is not showing up. Please see #198 for implementation, hopefully PR or steps are applied to canary.

**Comment by dmytrokhl** [comment]
We will check this. The problem here is that SwiftPM and CocoaPods use different Bundle or image resources. We should find solution that it works for all distribution frameworks.

**Comment by dmytrokhl** [comment]
SwiftPM need different bundle then CocoaPods. We are working on [workaround](https://github.com/verygoodsecurity/vgs-collect-ios/pull/209) to make it available when integrating SDK with each dependency manager.

**Comment by dmytrokhl** [comment]
@basememara we did update bundle resources in [v1.7.2](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.7.2).
