### ISSUE TITLE
Precompiled framework binary?

### ISSUE THREAD

**Issue by basememara** [verygoodsecurity/vgs-collect-ios#204]
In the release section, I don't see a framework binary to download. I only see the source code attached. Am I expected to compile the binary from source? What are the steps to do that?

**Comment by basememara** [comment]
I understand I can use a dependency manager, but for projects who cannot use a 3rd party dependency manager, what is the process of integrating the framework?

**Comment by dmytrokhl** [comment]
We will discuss internally adding Precompiled framework binary. This not quite popular distribution method these days, the main problems could come here with compatibility in different Xcode versions(if we build framework with future Xcode version, probably it couldn't work with previous versions.)
