### ISSUE TITLE
[ISSUE] Validation for expired date filed with calendar non gregorian  

### ISSUE THREAD

**Issue by hoangtuanfithou** [verygoodsecurity/vgs-collect-ios#217]
**Describe the bug**
If user choose calendar non Gregorian calendar in iPhone setting
-> SDK validation show error when check input for expire date field 

for example inside 
func vgsTextFieldDidChange(_ textField: VGSTextField) {
        -> textField.state.isValid -> return false
}

**Screenshots**

![image](https://user-images.githubusercontent.com/93890/105287023-5ae36f80-5bf2-11eb-91c3-6783a45e209f.png)

**Environment (please complete the following information):**
 - SDK Version 1.6.0
 - iOS Version: 14.4
 - Xcode Version: Xcode 12.3
 - Device: iPhone X

![image](https://user-images.githubusercontent.com/93890/105287069-6d5da900-5bf2-11eb-8685-ef3fca1b38c5.png)

**Comment by dmytrokhl** [comment]
Hi @hoangtuanfithou , this is [fixed](https://github.com/verygoodsecurity/vgs-collect-ios/blob/master/Sources/VGSCollectSDK/Utils/Extensions/Calendar%2Bextension.swift. ) starting from SDK v1.6.1.

**Comment by hoangtuanfithou** [comment]
Thank for your information. I will update the sdk. 🎉
