### ISSUE TITLE
[ISSUE] 403 Response when sending data from vgsCollect.sendData 

### ISSUE THREAD

**Issue by sha8wn** [verygoodsecurity/vgs-collect-ios#244]
**Describe the bug**
I have been using the VGS sandbox environment successfully over the last few days, now all of a sudden without any changes, I am getting a 403 error when making to call to VGSCollect.SendDate(path: , extraData: )

**To Reproduce**
1. Create 1 textfield with Configuration '...'
```
cardConfiguration.type = .cardNumber
cardConfiguration.isRequiredValidOnly = true
cardConfiguration.validationRules = VGSValidationRuleSet(rules: [
      VGSValidationRulePaymentCard.init(error: VGSValidationErrorType.cardNumber.rawValue, validateUnknownCardBrand: true)
    ])
cardNumberField.configuration = cardConfiguration
```
2. Click on Submit UI Button
3. Make a call to sendData(path: "/post", extraData: extraData)
4. See this response
```
failure(403, Optional(42 bytes), Optional(<NSHTTPURLResponse: 0x60000148ccc0> { URL: https://tntoxwh0eeq.sandbox.verygoodproxy.com/post } { Status Code: 403, Headers {
    "Access-Control-Allow-Origin" =     (
        "*"
    );
    "Content-Encoding" =     (
        br
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Tue, 23 Feb 2021 21:26:06 GMT"
    );
    Server =     (
        nginx
    );
    Via =     (
        "1.1 905b63dda002963cf44f2d6e390e1b3f.cloudfront.net (CloudFront)",
        "1.1 c193452bb546"
    );
    "vgs-request-id" =     (
        e20cbe7248d04c448d58c00499120e0c
    );
    "x-amz-apigw-id" =     (
        "bN7lTGM5IAMFnWQ="
    );
    "x-amz-cf-id" =     (
        "F-fJClXHykzbwTPqr8SD3wOCe0myNHeCff9fyNaZfyHOaAt1IDKfuw=="
    );
    "x-amz-cf-pop" =     (
        "IAD50-C2"
    );
    "x-amzn-errortype" =     (
        MissingAuthenticationTokenException
    );
    "x-amzn-requestid" =     (
        "be7e4723-5f6f-45ca-8258-da0714b7bdae"
    );
    "x-cache" =     (
        "Error from cloudfront"
    );
} }), nil)
```

**Expected behavior**
A success 200 response which I was getting before

**Screenshots**

**Environment (please complete the following information):**
 - SDK Version Where can I find this, I guess 1.7.0 
 - iOS Version: iOS 14.2
 - Xcode Version: 12.2
 - Device: iPhoneXs Max Simulator 
 - Dependency manager and it's version:
    - Cocoapods: 1.10.1

**Additional context**
I'm not sure if this is a temporary error or is it a usage issue or I am doing something wrong ?

Thanks in advance

**Comment by EugeneIOs** [comment]
Hello, @sha8wn.
Thank you for letting us know about the issue. We will try to reproduce it and provide feedback asap.
Could you please provide incoming request data as well with non-private some dummy but valid data?
As you got 403 error it can be related to permissions on VGS dashboard. Please check this.

Further steps might be taken:
1. Check logs on the dashboard for your <tenant_id>.
Please check this [instruction](https://www.verygoodsecurity.com/docs/features/audit-logs).

2. Try our latest SDK version (1.7.5).
It has helpful options for debugging. Check this [doc](https://www.verygoodsecurity.com/docs/vgs-collect/ios-sdk/debugging).

In you app delegate .init setup loggers. 

 Here is sample:
 
```swift
 	// Setup loggers in AppDelegate -init as the earliest app entry point.
	override init() {
		super.init()
 
 		// Enable loggers only for debug!
 		#if DEBUG
 		// Setup VGS Collect loggers:
 		// Show warnings and errors.
		VGSCollectLogger.shared.configuration.level = .warning
 
 		// Show network session for collect requests.
 		VGSCollectLogger.shared.configuration.isNetworkDebugEnabled = true

		// *You can stop all VGS Collect loggers in app:
		// VGSCollectLogger.shared.disableAllLoggers()
 		#endif
	}
```

**Comment by sha8wn** [comment]
Thanks for your response @EugeneIOs . When you say non private, do you also need the vaultId ? I am testing from the sandbox environment.

When I make the sendData request, I am sending some extra data in this format:
```
func getVGSPayload() -> [String: Any] {
    return ["user_id": userId, "system_user_id": systemUserId, "system_institution_id": systemInstitutionId]
}
```

Then I do this:
```
let extraData = vgsModel?.getVGSPayload() /// function above
EUXLog.log("VGS Payload: \(extraData ?? [String: Any]())")
    
/// send data to your Vault
vgsView.vgsCollect.sendData(path: "/post", extraData: extraData) { [weak self](response) in
```

Printing the dummy data I send as extra data from my logs to the console:
```
VGS Payload: ["mx_user_id": "U-d123cf623-5ecb-6c93-agO5-b8c4f0076ca9", "user_id": "t4Wq2fE4GQ19qGMm64vS", "mx_institution_id": "I-123erf456-wxyz-23d3-8f05-478527r974bx"]
```

Finally, since this is the sandbox environment and I only send the card data which is 4111 1111 1111 1111.

This was working fine yesterday morning so not sure if something changed 

In the mean time, I will update pods as you suggested.

Thank you.

**Comment by sha8wn** [comment]
@EugeneIOs - I have updated to 1.7.5 and get more logs and see the following:

```
⬆️ Send VGSCollectSDK request payload:
{
  "system_user_id" : "U-d123cf623-5ecb-6c93-agO5-b8c4f0076ca9",
  "system_institution_id" : "I-123erf456-wxyz-23d3-8f05-478527r974bx",
  "user_id" : "t4Wq2fE4GQ19qGMm64vS",
  "card_number" : "4111111111111111"
}
```

Then I see the issues:
```
❗Failed ⬇️ VGSCollectSDK request url: https://{sandboxVaultId}.sandbox.verygoodproxy.com/post
❗Failed ⬇️ VGSCollectSDK response status code: 403
❗Failed ⬇️ VGSCollectSDK response headers:
[
    Content-Encoding : br
    vgs-request-id : 778b5f2fc9e9ac2c50dc7346d3892609
    x-amz-cf-id : 6Tkiengw6Dksk6Pvhhrr4f3g2t6hMvOM0ZJF3UhplOpH9hMFRB02jA==
    Via : 1.1 5451b84324d9bca0bdd03e4c4009ae11.cloudfront.net (CloudFront), 1.1 704aa269718a
    x-amzn-requestid : e85253bc-a513-4791-9839-40becec07017
    x-amz-apigw-id : bPHbDHlpoAMFbSg=
    x-cache : Error from cloudfront
    Server : nginx
    Content-Type : application/json
    Date : Wed, 24 Feb 2021 06:03:50 GMT
    x-amz-cf-pop : IAD50-C2
    Access-Control-Allow-Origin : *
    x-amzn-errortype : MissingAuthenticationTokenException 
]
❗Failed ⬇️ VGSCollectSDK response extra info:
{"message":"Missing Authentication Token"}
```

Not sure if I need to add some auth token as I thought this was taken care of by using the vault id ? 

And also, this same request was working yesterday morning so I am a little lost on this one.

**Comment by EugeneIOs** [comment]
Thank you for providing more extensive debug information. We are on our way for checking it.

**Comment by EugeneIOs** [comment]
@sha8wn 
It seems there is an issue with your routes configuration on the dashboard. 
I'm not sure 403 error is related to SDK.

Please contact our support <support@verygoodsecurity.com> and we will try to help you asap.

**Comment by sha8wn** [comment]
Alright @EugeneIOs - thanks for your support, I will check with the support team.

Appreciate it.

**Comment by dmytrokhl** [comment]
@sha8wn I will close this issue since it's not related to SDK functionality. Our support team will help you to check Routs Configuration on Dashboard.
