### ISSUE TITLE
[FEATURE] Native SwiftUI Support

### ISSUE THREAD

**Issue by ericlewis** [verygoodsecurity/vgs-collect-ios#245]
**Is your feature request related to a problem? Please describe.**
SwiftUI is no longer new but the only way to use `vgs-collect-ios` with SwiftUI is a number of hacks or wrapping of the provided textfields. `VGSCollect` itself seems to rely on a storage that is based on `VGSTextField` which only extends UIView.

**Describe the solution you'd like**
It would be nice perhaps if there was more decoupling of view elements from `VGSCollect`, so we can work with it without needing UIKit.

**Describe alternatives you've considered**
It is completely possible to instead wrap the `VGSTextField` elements with `UIViewRepresentable`, but that leads to more annoying problems.

**Additional context**

**Possible solution**
Decouple the view elements from `VGSCollect`, decouple `VGSTextField` from `UIView`, and using a more composable architecture for interacting with `VGSCollect`.

**Comment by dmytrokhl** [comment]
@ericlewis SwiftUI support is definitely in our Roadmap, no ETA for now.

Note that if you collecting **PII** or other **sensitive data**, using custom UI elements that are not a part of `VGSCollectSDK` will put you into PCI scope. For other types of data, you can collect it with custom UI elements and send it with `extraData: [String: Any]` param in `VGSCollect.sendData(_:)` request.

**Comment by ericlewis** [comment]
@dmytrokhl oh wow, I didn't know that! thanks, for the time being we are wrapping VGSTextFields

**Comment by dmytrokhl** [comment]
We did release a [sample](https://github.com/vgs-samples/vgs-collect-show-ios-swiftUI-demo) how to use VGS Collect SDK in SwiftUI. 

Native SwiftUI SDK is still in our roadmap.

**Comment by dmytrokhl** [comment]
This is released in [v1.16.0](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.16.0).
