### ISSUE TITLE
[QUESTION] Any other test cards besides 4111 1111 1111 1111

### ISSUE THREAD

**Issue by sha8wn** [verygoodsecurity/vgs-collect-ios#247]
Hello VGS Team,

I currently need to test card types and depend on the last 4 digits of the card number being unique for some use cases so I just wanted to know if there was a database of dummy cards that I can use for testing purposes ?

Also, does anything need to be done when transitioning to the production environment besides changing the vault-id ?

Thanks

**Comment by dmytrokhl** [comment]
@sha8wn regarding test cards, you can use the one provided [here](https://github.com/verygoodsecurity/vgs-collect-ios/blob/master/Tests/FrameworkTests/Card%20Brand%20Tests/_CardBrandDataSource.swift).

**Comment by taras810** [comment]
@sha8wn , Please check our [Going live](https://www.verygoodsecurity.com/docs/getting-started/going-live#going-live) documentation regarding transitioning to the production environment. Please let us know if any additional assistance is required

**Comment by sha8wn** [comment]
Thanks @dmytrokhl and @taras810 for the very good support.
