### ISSUE TITLE
VGSCollectSDK (1.7.6) seems to crash on vgsView.vgsCollect.sendData(path: , extraData: )

### ISSUE THREAD

**Issue by sha8wn** [verygoodsecurity/vgs-collect-ios#252]
Hello VGS Team,

**Describe the bug**

I had a sample application that was using similar code from your samples 

I had a line of code like so:
```
vgsView.vgsCollect.sendData(path: "/notification", extraData: extraData) 
```

where vgsView is of type VGSView. On executing this line of code, the app crashes with:
![image](https://user-images.githubusercontent.com/1778742/112816175-2ed0e880-9092-11eb-9f53-edf4e0c36ed2.png)

**Expected behavior**
The app should not crash and send data to VGS. The same line of code works fine in 1.7.5

**Environment (please complete the following information):**
 - SDK Version [e.g. 1.7.6]
 - iOS Version: [e.g. iOS 14.4.1]
 - Xcode Version: [e.g. Xcode 12.4.]
 - Device: [e.g. iPad Air]
 - Dependency manager and it's version:
    - [ ] Cocoapods: [Latest]

**Comment by EugeneIOs** [comment]
Hi, @sha8wn.
Could you please provide:
- test project or sample with test data causing crash;
- steps to reproduce;
- more detailed crash info (crash log etc).

**Comment by EugeneIOs** [comment]
@sha8wn 

You can also send test project with you [app](https://github.com/getBanyan/by_mobile_ios_framework_connect_demo_app)
to support@verygoodsecurity.com if you don't want to expose some private info here.

We need:
1. demo app version with issue.
2 test credentials (API key etc) - as I see we need some credentials to run your demo app. 
3 detailed steps how to replicate problem.

**Comment by sha8wn** [comment]
@EugeneIOs - I will definitely support you with this, however it will be during the course of the week as I just have some things to finish up.

I will try to recreate this in isolation and share the sample project with you so if possible, please keep this issue open till I do so.

Thank you for your support.

**Comment by EugeneIOs** [comment]
@sha8wn 
sure, we will wait for your sample and this issue open as well.

**Comment by dmytrokhl** [comment]
Closed due to inactivity.
