### ISSUE TITLE
[ISSUE] VGSSdk 1.7.11 causes build failure

### ISSUE THREAD

**Issue by rubina-shakhkyan** [verygoodsecurity/vgs-collect-ios#269]
**Describe the bug**
A clear and concise description of what the issue is.
Located in file `Core/VGSCollectLogger.swift`

**To Reproduce**
Build project from xcode 12.5

**Screenshots**
![Screenshot 2021-05-03 at 11 17 50](https://user-images.githubusercontent.com/64727687/116862686-6e48a280-ac05-11eb-83ca-67a3bb96bb98.png)

**Environment (please complete the following information):**
 - SDK Version 1.7.11
 - iOS Version: iOS 14.2 / 14.4
 - Xcode Version:12.5

**Comment by EugeneIOs** [comment]
Hello @rubina-shakhkyan 
Thank you for informing us about this issue.
We will have a look to this.

Could you please also tell us how do you integrate VGS Collect SDK?
CocoaPods/SPM/Carthage?

**Comment by rubina-shakhkyan** [comment]
> Hello @rubina-shakhkyan
> Thank you for informing us about this issue.
> We will have a look to this.
> 
> Could you please also tell us how do you integrate VGS Collect SDK?
> CocoaPods/SPM/Carthage?

Thank you for a prompt reply. I integrate it using CocoaPods in a .podspec file.

**Comment by EugeneIOs** [comment]
@rubina-shakhkyan 
Tried with latest Xcode 12.5 and different simulators/test projects, cannot reproduce.
My assumption it can be replicated with some specific build settings.

Could you please provide some simple test project with the issue?

**Comment by rubina-shakhkyan** [comment]
Accidentally tried to compile the project to Swift v4.2, fixed after switching swift compiler version.
