### ISSUE TITLE
[FEATURE] Setting the max length on VGSTextField

### ISSUE THREAD

**Issue by dorastipkovic** [verygoodsecurity/vgs-collect-ios#295]
**Is your feature request related to a problem? Please describe.**
I'm using a VGSTextField UI component with `VGSConfiguration.type = FieldType.none` for inserting user address information, when adding a new credit card. I would like to set the max length of the input so that the user can type e.g. 40 characters and the rest to be discarded. 

**Describe the solution you'd like**
Ideally we could would be able to call VGSTextField.setMaxLength(X) and that would limit the number of characters a user can type in the field. That is already implement on Android in `com.verygoodsecurity.vgscollect.widget.VGSEditText`

**Describe alternatives you've considered**
I was able to add a VGSValidationRuleLength, but that just invalidates the state and the user can still type more than max length.

**Comment by dmytrokhl** [comment]
@dorastipkovic we add `.maxInputLength` feature in VGSCollectSDK [v1.9.3](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.9.3).
