### ISSUE TITLE
[ISSUE] Crash in APIClient upon deinit

### ISSUE THREAD

**Issue by myeyesareblind** [verygoodsecurity/vgs-collect-ios#299]
**Describe the bug**
The crash happens in a popular iOS application that uses VGS. See attached stack trace.

**To Reproduce**
I haven't tried, from what I see is:
https://github.com/verygoodsecurity/vgs-collect-ios/blob/52f0bba547a885ddb7fe22d7bf11514b34652633/Sources/VGSCollectSDK/Core/API/APIClient.swift#L201 gets called few times.
While semaphore is locked, APIClient gets dealloced, which produces a [crash](https://stackoverflow.com/questions/8287621/why-does-this-code-cause-exc-bad-instruction)

**Expected behavior**
Should not crash

**Screenshots**

**Environment (please complete the following information):**
 - SDK Version [1.9.1]
 - iOS Version: [iOS 14.4.2]
 - Xcode Version: [Xcode 13.1]
 - Device: [iPhone 8]
 - Dependency manager and it's version:
    - [x] Cocoapods: [1.10.2]
    - [ ] Carthage: [e.g.  0.34.0]

**Possible Solution**
Change the logic. Either use NSOperationQueue to limit number of concurrent operation or use a dedicated queue of requests.

[crash-log.txt](https://github.com/verygoodsecurity/vgs-collect-ios/files/7526811/crash-log.txt)

**Comment by EugeneIOs** [comment]
@myeyesareblind 
Hi, this issue has been fixed in [1.9.2](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.9.2).
Please update your apps to the latest SDK version.

**Comment by myeyesareblind** [comment]
Thanks, @EugeneIOs ! I'm looking at d6855a6ab9c5b12dd2b42e503f429f0cb00bf115 commit.

Could you elaborate how/why is it fixed? Perhaps I miss something.
As far as I see:
With that fix, APIClient might be deallocated before async. Which is an improvement.
It doesn't however fix the root cause.

Here is the sample test I came up with, that demonstrates the problem. 
It's a bit tricky. See the sample test case
What happens is APIClient gets deallocated while semaphore value is 0.

Please let me know if I have missed anything.
<img width="1272" alt="Screenshot 2021-11-12 at 13 16 19" src="https://user-images.githubusercontent.com/575303/141458730-f54b0e4b-17d4-4c8e-a322-838c72f696a1.png">

test-case:
[SampleAppTests 3.swift.zip](https://github.com/verygoodsecurity/vgs-collect-ios/files/7527157/SampleAppTests.3.swift.zip)

**Comment by EugeneIOs** [comment]
@myeyesareblind 
It is not an improvement but fix.

While fixing this bug in our previous versions we replicated 100% the same crash in our demo app with following steps:
1. use `customHostname` in VGSCollectSDK `init` method;
2. simulate small delay in the `init` method where updateHost is called with`Dispatch.asyncAfter`;
3. close screen so VGSCollectSDK is called.
So `deinit` of `VGSCollectSDK` will be trigger internal crash of `libdispatch` with `semaphore object deallocated while in use`.

`Weak self/strongSelf` will fix this issue.

**Comment by myeyesareblind** [comment]
@EugeneIOs ,

steps to reproduce are different to what you've described.

Here there are 2 calls:
1st succeeds (wait/signal)
2nd is started (wait goes through and async is called).
object gets deallocated while semaphore value is 0 = crash

**Comment by EugeneIOs** [comment]
@myeyesareblind 
Could you please provide steps to replicate this issue with our demo app?

**Comment by myeyesareblind** [comment]
I cannot replicate it in the demo app.
Perhaps because host resolve is not triggered,
or because this issue happens to 100 users out of 10 millions and is quite hard to replicate due to timings.

We certainly can try updating to 1.9.2, yet the issue is likely to be there as pointed out in the sample app.

**Comment by EugeneIOs** [comment]
Please let us know if you can provide more details about this issue after updating to `1.9.2`

**Comment by EugeneIOs** [comment]
Closed due to cannot reproduce.

**Comment by nikolaykasyanov** [comment]
Hey folks,

we're also experiencing it on 1.9.2. If anything, fixing the retain cycle might have made the crash more likely because the only way to get it is to let the client deallocate.

I wonder if using regular locks has been considered to completely avoid dealing with the "deallocating semaphore while in use" thing?

**Comment by EugeneIOs** [comment]
@nikolaykasyanov 
Thank you for letting us know and help with investigating it.
we released fix in [1.9.5](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.9.5).
