### ISSUE TITLE
[ISSUE] SwiftUI preview builds fail due to missing Foundation import

### ISSUE THREAD

**Issue by fabianmuecke** [verygoodsecurity/vgs-collect-ios#352]
**Describe the bug**
In a Swift package, which depends on vgs-collect-ios, I cannot use SwiftUI previews. The preview build fails, because `CharacterSet.decimalDigits` cannot be found. `CharacterSet` is part of `Foundation`, which is not imported in the file `VGSDateFormat.swift`.

**To Reproduce**
1. Create Swift package with a SwiftUI view
2. Add dependency to vgs-collect-ios
3. Try to use SwiftUI preview

**Expected behavior**
The preview build should not fail.

**Screenshots**
<img width="1372" alt="image" src="https://github.com/verygoodsecurity/vgs-collect-ios/assets/317346/65735cb3-7d6f-4752-bf53-b223b4245763">

**Environment (please complete the following information):**
 - SDK Version: latest master
 - iOS Version: [e.g. iOS 13.1+]
 - Xcode Version: 14.3.1
 - Device: e.g. iPhone 14 Pro Simulator target
 - Dependency manager and it's version:
    - [x] SPM

**Possible Solution**
Add `import Foundation` to `VGSDateFormat.swift`. Pull request incoming… 🙃

**Comment by dmytrokhl** [comment]
@fabianmuecke thanks, we will take a look.
