### ISSUE TITLE
[ISSUE] - Compiler warning with latest `PrivacyInfo.xcprivacy` file included in "sources" of podspec.

### ISSUE THREAD

**Issue by gerry-wood-sumup** [verygoodsecurity/vgs-collect-ios#386]
**Describe the bug**
First, thank you for adding the `PrivacyInfo.xcprivacy` file to the repo, it is much appreciated.

What I am seeing is the compiler is throwing the below warning when using Cocoapods. 

It appears the file has been included as a "source" file in the [podspec](https://github.com/verygoodsecurity/vgs-collect-ios/blob/master/VGSCollectSDK.podspec#L25). 

Looking at a similar [issue](https://github.com/firebase/firebase-ios-sdk/issues/12511) for FirebaseMessaging, it seems [this PR ](https://github.com/firebase/firebase-ios-sdk/pull/12513) ensured to only include the files with proper suffixes of {m, h and c} - which VGS is already handling. 

After investigating further, it seems they have included the `PrivacyInfo.xcprivacy` file as a "resource" instead, where the VGS xcprivacy file is included as a "source" file in the [podspec](https://github.com/verygoodsecurity/vgs-collect-ios/blob/master/VGSCollectSDK.podspec#L25).

**To Reproduce**
1. Create an empty project and configure for Cocoapod use
2. Run project and observe Warning as shown below

**Expected behavior**
No warning should be present, some CI systems will fail if warnings are not allowed.

**Screenshots**
<img width="458" alt="image" src="https://github.com/verygoodsecurity/vgs-collect-ios/assets/100949190/5aa041e4-8ef0-423b-ac8b-f6bd5c681e13">

**Environment (please complete the following information):**
 - SDK Version [e.g. 1.16.1]
 - iOS Version: [e.g. iOS 13+]
 - Xcode Version: [e.g. Xcode 15.3]
 - Device: [e.g. iPhone 15 pro]
 - Dependency manager and it's version:
    - [ X] Cocoapods: [e.g.  1.15.2]
    - [ ] Carthage: [e.g.  0.34.0]

**Additional context**

**Possible Solution**
If you have the solution how to fix the issue.

**Comment by dmytrokhl** [comment]
@gerry-wood-sumup thanks for your investigation. I will take a look and let you know when it's fixed.

**Comment by dmytrokhl** [comment]
@gerry-wood-sumup this is fixed in [v1.16.2](https://github.com/verygoodsecurity/vgs-collect-ios/releases/tag/1.16.2).
